server:
 servlet:
    context-path: /produdoro/api
    
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://produdoroDevUser:8iN1yCBRKXMRZa1A@cluster0.bbnoj.mongodb.net/produdoroDevDB?retryWrites=true&w=majority}
      auto-index-creation: true      

springdoc:
  swagger-ui:
    path: /public/swagger

 
produdoro:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}